### ISSUE TITLE
Annotations for the 2021 article will be made available soon?

### ISSUE THREAD

**Issue by sanli0** [majrie/pig_detection#1]
When is the exact time?

**Comment by majrie** [comment]
Thanks for your interest in my work. Yes, I am working on publication. I will reply as soon as it will becomes available.

**Comment by majrie** [comment]
Thanks for your interest in our work. I am working on publishing the dataset and it will be available soon. I will reply here as soon as it becomes available.

**Comment by majrie** [comment]
You can download the dataset here: https://github.com/majrie/pig_detection_dataset/raw/main/COMPAG_106213_Riekert_et_al_2021.zip

The repository that contains the file can be found here: https://github.com/majrie/pig_detection_dataset
